eureka:
  instance:
    hostname: gateway
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8200/eureka/,http://admin:admin@localhost:8201/eureka/
#log
logging:
  level:
    com:
      huidong:
        qzh: warn
#          mapper: error
  file: logs/qzh-api-gateway.log