spring:
  application:
    name: qzh-store
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
   # default-property-inclusion: non_default / non_null
#mybatis:
#    type-aliases-package: com.huidong.qzh.portal.entity
#    mapper-locations: classpath:mapper/*.xml
#mapper:
#    mappers:
#        - com.huidong.qzh.portal.util.MyMapper
#    not-empty: false
#    identity: MYSQL
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql