server:
  port: 80
#  ssl:
#    key-store: classpath:www.sceo360.com.jks
#    key-password: huidong123
---
spring:
  application:
    name: qzh-load-balance
  http:
    multipart:
      max-file-size: 2000Mb #文件上传大小限制
      max-request-size: 2500Mb #文件下载大小限制

---
zuul:
  sensitive-headers:
  routes:
    gateway:
      path: /api/**
      serviceId: qzh-api-gateway
  host:
      connect-timeout-millis: 60000
      socket-timeout-millis: 60000
ribbon:
  eureka:
    enabled: false
qzh-api-gateway:
  ribbon:
      listOfServers: localhost:8100


---
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
              timeoutInMilliseconds: 60000
---
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
---
# log
logging:
  level:
    com:
      qzh: debug
  file: logs/qzh-load-balance.log

