# 节点1
spring:
  profiles:
    active: peer1
server:
  port: 8200
eureka:
  instance:
    hostname: register-server1
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8201/eureka/

