spring:
  application:
    name: qzh-standard
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: 2000Mb #文件上传大小限制
      max-request-size: 2500Mb #文件下载大小限制
   # default-property-inclusion: non_default / non_null
#mybatis:
#    type-aliases-package: com.huidong.qzh.portal.entity
#    mapper-locations: classpath:mapper/*.xml
#mapper:
#    mappers:
#        - com.huidong.qzh.portal.util.MyMapper
#    not-empty: false
#    identity: MYSQL
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
---
# zipkin 监控
spring:
  zipkin:
    base-url: http://localhost:8600
  sleuth:
    sampler:
      percentage: 1
---
# rabbitMq
spring:
  rabbitmq:
    host: 192.168.100.73
    port: 5672
    username: root
    password: huidong123